project:
  type: website
  output-dir: docs

website:
  title: "Fluid Mechanics Laboratory (Fall 2025)"
  page-footer: "This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br> Contact: [Kartik Bulusu](mailto:bulusu@email.gwu.edu)<br> &copy; 2025 All rights reserved"
  search: true
  page-navigation: true
  bread-crumbs: true
  sidebar:
    style: floating
    # collapse-level: 2
    contents: 
      - href: index.qmd
        text: Home
      # - href: guidelines.qmd
      #   text: Course Guidelines and Student Responsiblities
      - href: objectives.qmd
        text: Learning Objectives  
      - href: policies.qmd
        text: Grading and Course Policies             
      - href: agenda.qmd
        text: Schedule 
      - href: instructor.qmd
        text: Instruction Team

      # - section: "Getting Started (Prerequisites)"
      #   contents: 
      #     - href: install-editor.qmd
      #       text: Installations on your personal machine
      #     - section: "Real VNC&reg; Viewer"
      #       contents: 
      #         - href: realvnc-mac.qmd
      #           text: Mac
      #         - href: realvnc-windows.qmd
      #           text: Windows   
      #     - href: thingspeak.qmd
      #       text: ThingSpeak
      #     - section: "Connecting your laptop to the Raspberry Pi"
      #       contents: 
      #         - href: realvnc-mac-connect.qmd
      #           text: Mac
      #         - href: realvnc-windows-connect.qmd
      #           text: Windows                       


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    author: Kartik Bulusu
    date: now
    # monofont: "DejaVu Sans Mono"
    # mainfont: "Roboto"



